[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
insecure_update_project2 = "4cAcyYDHcBnKEWgFbmMbsz8qNTriBH3cNrGdqi91Qh4s"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
